using UnityEngine;

[CreateAssetMenu(menuName = "Weapon/Weapon Data Explosive", fileName = "WeaponDataExplosive")]
public class WeaponDataExplosive : ScriptableObject
{
    [Header("Explosive Attributes")]
    [Tooltip("The radius of the explosion generated by a projectile fired from this weapon upon impact.")] public float[] radius;
}
