using UnityEngine;

[CreateAssetMenu(fileName = "WeaponDataProjectile", menuName = "Weapon/Weapon Data Projectile")]
public class WeaponDataProjectile : WeaponData
{
    [Header("Projectile Weapon Attributes")]
    [Tooltip("The projectile fired from this weapon.")] public GameObject projectile;
    [Tooltip("The speed with which a projectile fired from this weapon moves.")] public float speed;
    [Tooltip("The radius of the explosion generated by a projectile fired from this weapon upon impact.")] public float radius;
    [Tooltip("The life span of a projectile fired from this weapon.")] public float lifeSpan;
}
